---
abstract: 'Adds CPAN Testers reporting to CPAN.pm'
author:
  - 'David A. Golden <dagolden@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Reporter
no_index:
  directory:
    - examples
    - inc
provides:
  CPAN::Reporter:
    file: lib/CPAN/Reporter.pm
    version: 1.1801
  CPAN::Reporter::Config:
    file: lib/CPAN/Reporter/Config.pm
    version: 1.1801
  CPAN::Reporter::History:
    file: lib/CPAN/Reporter/History.pm
    version: 1.1801
  CPAN::Reporter::PrereqCheck:
    file: lib/CPAN/Reporter/PrereqCheck.pm
    version: 1.1801
requires:
  CPAN: 1.9301
  Config::Tiny: 2.08
  Devel::Autoflush: 0.04
  ExtUtils::MakeMaker: 6.36
  File::Basename: 0
  File::Copy::Recursive: 0.35
  File::Find: 0
  File::HomeDir: 0.58
  File::Path: 0
  File::Spec: 3.19
  File::Temp: 0.16
  File::pushd: 0.32
  IO::CaptureOutput: 1.03
  Parse::CPAN::Meta: 0
  Probe::Perl: 0
  Tee: 0.13
  Test::More: 0.62
  Test::Reporter: 1.54
resources:
  license: http://www.apache.org/licenses/LICENSE-2.0.txt
version: 1.1801
